scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: zb
  scrape_interval: 1s
  metrics_path: /zeebe.prom
  scheme: http
  static_configs:
  - targets:
    ##### Specify YOUR AWS public DNS names of your brokers here, easist is just to copy them from ansible
    - ec2-35-158-248-190.eu-central-1.compute.amazonaws.com
    - ec2-18-184-212-174.eu-central-1.compute.amazonaws.com
    - ec2-18-184-225-95.eu-central-1.compute.amazonaws.com
    - ec2-18-197-199-229.eu-central-1.compute.amazonaws.com
    - ec2-18-184-197-7.eu-central-1.compute.amazonaws.com
    - ec2-18-184-254-124.eu-central-1.compute.amazonaws.com
    - ec2-35-158-10-135.eu-central-1.compute.amazonaws.com
    - ec2-52-58-254-55.eu-central-1.compute.amazonaws.com
    - ec2-52-57-139-210.eu-central-1.compute.amazonaws.com
    - ec2-18-194-67-207.eu-central-1.compute.amazonaws.com
    - ec2-18-196-249-6.eu-central-1.compute.amazonaws.com
    - ec2-18-184-9-245.eu-central-1.compute.amazonaws.com
    - ec2-18-184-104-10.eu-central-1.compute.amazonaws.com
    - ec2-18-184-251-7.eu-central-1.compute.amazonaws.com
    - ec2-18-184-217-65.eu-central-1.compute.amazonaws.com
    - ec2-18-197-127-180.eu-central-1.compute.amazonaws.com
    - ec2-18-185-15-144.eu-central-1.compute.amazonaws.com
    - ec2-18-185-10-22.eu-central-1.compute.amazonaws.com
    - ec2-18-195-232-187.eu-central-1.compute.amazonaws.com
    - ec2-18-184-207-96.eu-central-1.compute.amazonaws.com
    - ec2-52-28-51-149.eu-central-1.compute.amazonaws.com
    - ec2-35-156-165-48.eu-central-1.compute.amazonaws.com
    - ec2-18-195-10-112.eu-central-1.compute.amazonaws.com
    - ec2-18-184-183-14.eu-central-1.compute.amazonaws.com
    - ec2-35-158-86-91.eu-central-1.compute.amazonaws.com
    - ec2-18-197-137-118.eu-central-1.compute.amazonaws.com
    - ec2-18-184-113-164.eu-central-1.compute.amazonaws.com
    - ec2-18-185-8-21.eu-central-1.compute.amazonaws.com
    - ec2-18-184-84-139.eu-central-1.compute.amazonaws.com
    - ec2-18-197-41-16.eu-central-1.compute.amazonaws.com
